replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIp
  port: 80

ingress:
  enabled: true
  className: "alb"  # Set to "alb" for AWS Application Load Balancer
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: "internet-facing" # or "internal" if you want internal ALB
    alb.ingress.kubernetes.io/target-type: "ip"
    alb.ingress.kubernetes.io/group.name: "nginx-group"
    alb.ingress.kubernetes.io/group.order: "1"
  hosts:
    - host: example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
